services:
  nginx:
    image: jwilder/nginx-proxy
    restart: unless-stopped
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    volumes:
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - nginx-certificates:/etc/nginx/certs:ro      
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy_network
    logging:
      options:
        max-size: 50m

  nginx-letsencrypt-companion:
    restart: unless-stopped
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - vhost:/etc/nginx/vhost.d  
      - html:/usr/share/nginx/html 
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-certificates:/etc/nginx/certs:rw
    environment:
      - NGINX_PROXY_CONTAINER=${COMPOSE_PROJECT_NAME}-nginx
      - DEFAULT_EMAIL=${ADMIN_EMAIL}

volumes:
  nginx-certificates:
  vhost:
  html:
  dhparam:

networks:
  proxy_network:
    external: false
    name: nginx_network


