# https://doc.traefik.io/traefik/reference/static-configuration/file/

global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  web:
    address: :80

  websecure:
    address: :443
    http:
      tls:
        certResolver: letsencrypt
    http3: {}

log:
  level: ERROR

api:
  insecure: true

providers:
  docker:
    exposedByDefault: false
    network: proxy_network

certificatesResolvers:
  letsencrypt:
    acme:
      dnsChallenge:
        entrypoint: web
      email: ${ADMIN_EMAIL}
      storage: /letsencrypt/acme.json
